### ISSUE TITLE
Is there any documentation

### ISSUE THREAD

**Issue by fcabaud** [suer/redmine_issues_summary_graph#14]
Hello

  How this plug is working ?

Thanks

**Comment by suer** [comment]
No. The document is README only.

To use this plugin, please set project settings and permissions.
ImageMagick is also required.

Pull Requests are also welcome!

**Comment by fcabaud** [comment]
ImageMagick is already installed.

In admin/plugins there is no setting menu on the left for this plugin.

**Comment by suer** [comment]
Yes. This plugin has no setting menu.

You can enable this plugin by turning module setting on in projects setting.

**Comment by fcabaud** [comment]
OK, I saw it.
Thank you so much.
